#!/bin/bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen
read -p "How many files do you want to create? " fileamount
for n in {1..${fileamount}}; do
	dd if=/dev/urandom of=file$( printf %03d "$n" ).bin bs=1 count=$(( RANDOM + 1024 ))
done
