#!/bin/bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen

read -p "How big in gb should the file be? (just write a number) " filesize
read -p "What do you want to call the file? " filename
if [ -z $filesize ] || [ -z $filename ];then
	echo "You did not specify a size or name..."
	exit 1
else 
	truncate -s ${filesize}G $filename
fi
