#!/bin/bash
# Author Daniel "fauen" Bäckman
# https://github.com/fauen

# This will just copy the config and open an editor so you can make the changed you want.

if ! [ -d /home/$USER/.config/wtf/ ]; then
	mkdir /home/$USER/.config/wtf
else
	exit 1
fi

if [ -d /home/$USER/dotfiles/ ]; then
	cp /home/$USER/dotfiles/wtf-config.yml /home/$USER/.config/wtf/config.yml
else
	echo "You don't have the dotfiles repo"
	exit 1
fi	

# This will open your preferred editor and edit the config
if [ -e /home/$USER/.config/wtf/config.yml ]; then
	$EDITOR /home/$USER/.config/wtf/config.yml
else
	exit 1
fi
